### ISSUE TITLE
Impl Traffic Shaping

### ISSUE THREAD

**Issue by raulk** [ipfs/testground#29]
We need an API/tool to declaratively enforce traffic shaping rules via `tc`. Think of this as Terraform for traffic shaping. It takes an object (serializable into JSON or YAML or whatever), and applies the rules expressed within. It then exposes an API to "release" those rules and revert the network adaptor.

**Comment by jimpick** [comment]
Here are some basic `tc` commands for various scenarios:

https://wiki.linuxfoundation.org/networking/netem

We probably need just basic traffic shaping for initial bitswap tests.

**Comment by raulk** [comment]
Some API design notes.

I'd design a series of structs or DTOs with a top-level struct that acts like a "blueprint"/config object. They can be marshalled/unmarshalled via different libraries.

I'd create a `Binding` interface that binds fields to `tc` actions.

```
type Binding interface {
    // Enforce takes the value of the field and creates the tc incantation to apply the rule.
    Enforce() (string, error)

    // Rollback takes the value of the field and creates the tc incantation to roll back the rule.
    Rollback() (string, error)
}
```

For each aspect we want to configure, e.g. latency, bandwidth, jitter, etc. I'd create an implementation of the interface. If we make all implementing types strings, we get the JSON serde for free, e.g.:

```
type JitterBinding string

func (b *JitterBinding) Enforce() (string, error) {
    return fmt.Sprintf("tc %s %s %s", b, b, b), nil
}

func (b *JitterBinding) Rollback() (string, error) {
    ...
}

type Declaration struct {
    Jitter JitterBinding
    Bandwidth BandwithBinding
    ...
}
```

When we apply a traffic shaping declaration, we'd invoke all the bindings for all elements that appear in it, collate them into a script, and execute that script. Same for rollback.

How does that sound, @jimpick?

**Comment by jimpick** [comment]
Looks good. I'll experiment next week.

**Comment by jimpick** [comment]
There's also https://github.com/Shopify/toxiproxy ... used in https://github.com/JGAntunes/ipfs-testbed

One limitation of `tc` is that it will only work on Linux ... the proxy approach might work for developers developing on OS X and Windows.

**Comment by daviddias** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Implement minimal `tc` traffic shaping](https://trello.com/c/bOL4c0dy/31-implement-minimal-tc-traffic-shaping)

**Comment by Stebalien** [comment]
In progress: PR #143 

* [x] **P0**: Communication via redis
* [x] **P0**: Applies network configuration changes
  * [x] **P0**: Bandwidth
  * [x] **P0**: Latency
  * [ ] **P2**: Multiple Subnets
* [ ] **P1**: Docker Local
  * [x] **P1**: Watches docker start/stop events
  * [ ] **P1**: Deployment
* [ ] **P0**: Docker Swarm
  * [x] **P0**: Watches docker start/stop events
  * [ ] **P0**: Deployment
* [ ] **P1**: Local
  * [ ] **P1**: Watch for new nodes.
  * [ ] **P1**: Deployment.
* [ ] **P3**: Nomad
  * [ ] **P3**: Deployment
  * [ ] **P3**: Watch for new nodes

**Comment by Stebalien** [comment]
Status: It can now shape traffic, I think. However, I'm still trying to get libp2p to not use the control network.

**Comment by raulk** [comment]
Traffic shaping has now been implemented. We can set jitter, latency, loss, corruption, reordering, duplication.
