### ISSUE TITLE
prepare release v0.4.0 (contains checklist)

### ISSUE THREAD

**Issue by Robmat05** [ipfs/testground#794]
## Manual release process checklist (in order).

Release performed off branch `release/v0.4.0`.

```
NEW_VERSION=v0.4.0
```

- [x] Tag release branch as `sdk/runtime/$NEW_VERSION`.
- [x] Push the `sdk/runtime/$NEW_VERSION` tag.
- [x] Delete all replace directives from all `go.mod`s.
- [x] In `sdk/iptb`, `go get github.com/ipfs/testground/sdk/runtime@$NEW_VERSION && go mod tidy`.
- [x] In `sdk/sync`, `go get github.com/ipfs/testground/sdk/runtime@$NEW_VERSION && go mod tidy`.
- [x] In root, `go get github.com/ipfs/testground/sdk/runtime@$NEW_VERSION && go mod tidy`.
- [x] In `sdk/sync/go.mod`, manually bump the reference to `testground` to `$NEW_VERSION`.
- [x] In `testground/go.mod`, manually bump the reference to `sdk/sync` to `$NEW_VERSION`.
- [x] git commit and push all changes with message "release $NEW_VERSION."
- [x] Use git CLI to tag `sdk/sync/$NEW_VERSION` and `sdk/iptb/$NEW_VERSION` from release branch.
- [x] Push those tags to origin.
- [x] Use the GitHub UI to produce the `testground` `$NEW_VERSION` release by publishing the Github Release based from the release/$NEW_VERSION branch, with a nicely formatted change log and all.
- [x] Bump versions in master.
