### ISSUE TITLE
Impl Plan - Chew Datasets

### ISSUE THREAD

**Issue by daviddias** [ipfs/testground#93]
Plan Description: https://github.com/ipfs/testground/tree/master/plans/chew-large-datasets

Previous Trello Card URL for context: https://trello.com/c/NFVwUcm6/35-impl-plan-1-chewing-strategies-for-large-datasets

**Comment by hacdias** [comment]
# Status 

This is the tracking comment of this issue where the **status** will be published and **updated**.

## What's being done

- [ ] Using API only
	- [x] IPFS Add Defaults (#58)
	- [x] IPFS IPFS Add Trickle DAG (#58)
	- [x] IPFS Add Dir Sharding (#58)
	- [ ] IPFS MFS Write
	- [ ] IPFS MFS Dir Sharding
	- [ ] IPFS Url Store
	- [ ] IPFS File Store
- [ ] Using external daemon/IPTB
	- [x] IPFS Add Defaults (#223)
	- [x] IPFS IPFS Add Trickle DAG (#223)
	- [x] IPFS Add Dir Sharding (#236)
	- [ ] IPFS MFS Write
	- [ ] IPFS MFS Dir Sharding
	- [ ] IPFS Url Store
	- [ ] IPFS File Store
	
## Related issues and walls

- [ ] How to add a directory with sharding enabled? https://github.com/ipfs/interface-go-ipfs-core/issues/48
- [x] `Too many open files` https://github.com/ipfs/go-ipfs/issues/6780
- [ ] How to run GC? https://github.com/ipfs/kubo/issues/9971
- [ ] How to add files to MFS? https://github.com/ipfs/interface-go-ipfs-core/issues/53
	- [ ] Core implementation https://github.com/ipfs/go-ipfs/pull/6786
	- [ ] Core API https://github.com/ipfs/interface-go-ipfs-core/pull/54
- [ ] How to use FileStore API? https://github.com/ipfs/interface-go-ipfs-core/issues/55

## Notebook and random stuff

```console
go build && ./testground run chew-large-datasets/ipfs-add-defaults \
	--runner local:exec \
	--builder exec:go \
	--build-cfg bypass_cache=true \
	--test-param dir-cfg='[{"depth": 10, "size": "1MB"}, {"depth": 15, "size": "1MB"}]' \
	--test-param file-sizes='["1MB"]'
```
